export const data: string = `
<p>This Privacy Policy discloses the privacy practices for www.luminarcapital.com and applies solely to information collected through this website (Site).<br/>
We reserve the right to change this Privacy Policy from time to time. The Privacy Policy is subject to and incorporates by reference our Terms of Service, including its limitation on liability.<br/>
Your use of our Site and provision of Personal Information online constitutes acceptance and understanding of this Policy as in effect at the time of your submission.</p>
<h4>Types Of Personal Information We Collect</h4>
<p>We do not collect personal information from visitors to our Site unless you voluntarily decide to transmit it to us through one of the Site features, provided e-mail addresses or as part of an application. Certain features of our Site may require you to create an account. When you create an account with us, we may collect your name, email address, contact information, a username and password that you will use to access your account and other information. In addition, to submit a question, comment, or post to a blog, you may be required to submit your name and email address, and we may also ask you for other optional information, such as your business’s website address.</p>
<p>We also collect the following types of information (personal or otherwise) through the Site:</p>
<ul>
	<li>Information provided on an application;</li>
	<li>Information to verify an individual’s identity (e.g., social security number, an unexpired government identification with a photo, user name and password, etc.);</li>
	<li>Information about your visits to and use of this Site or the websites of third-party servicers to help us maintain the appropriate features, functionality, and user experience;</li>
	<li>Individual and business financial or credit bureau information;</li>
	<li>Personal Information contained in government filings or legal agreements (e.g., corporate formation agreements, business licenses, lease or loan agreements, and business tax returns);</li>
	<li>Any other personal information you submit or upload through our Site or to one of our email addresses, including information you post to our Site in a comment, blog or testimonial;</li>
	<li>The website from which you came to our Site and your IP address, browser type and other information related to the device from which you accessed the Site;</li>
	<li>Your or your business’s geolocation, through various GPS or other geolocator tools that use the IP address of your device to detect a user’s location; </li>
	<li>Information collected through our Site data or through an ISO (independent sales organization), or other data that we receive from other sources, such as public records, and other background information supplied by information services or third parties.</li>
</ul>
<h4>What We Do With The Personal Information Collected</h4>
<p>No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. All the stated categories in this privacy policy exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties. End users can opt out of receiving further messages by replying STOP or ask for more information by replying HELP. Message frequency may vary. Message and data rates may apply</p>
<p>We may disclose personal information to third parties for the following purposes:</p>
<ul>
	<li>In response to a subpoena or other legal process by a governmental entity or third party, or if otherwise required by law;</li>
	<li>To protect or enforce our rights or property;</li>
	<li>In the event of the sale or dissolution (bankruptcy) of all of our assets, in which case, you will be notified thereafter by a prominent notice on our Web site of any change in ownership or uses of your personal information, as well as any choices you may have regarding your personal information;</li>
	<li>To third parties involved in the process of providing services to us or you or performing functions on our behalf, such as contractors, customer service providers, credit bureaus, and collection agencies. Those contractors and service providers are permitted to use your personal information only for the purpose for which it has been provided and may not disclose it to any other third party except at our express direction and in accordance with this Privacy Policy;</li>
	<li>To our affiliates and subsidiaries for marketing, advertising, research, or other business purposes;</li>
	<li>To the ISO that referred you to us—for example, in connection with reporting on your progress in the application process or in connection with calculating or reporting on the commission due to the referral source or otherwise;</li>
	<li>To provide information or promotional material that may be of interest to you;</li>
	<li>To our investors, partners, or auditors in the course of their review or auditing us;</li>
	<li>To provide you with products or services requested, either from us or from Luminar’s network of external funding partners;</li>
	<li>To our vendors, who may use the information to further improve their database services to us.</li>
</ul>
<p>If, at any time, you would like to stop receiving these promotional e-mails, you may follow the opt-out instructions contained in any such e-mail. Please note that it may take up to 10 business days for us to process opt-out requests. If you opt-out of receiving emails or promotions from us, we still may send you e-mails about your account, your application or any products or services you have requested or received from us, or for other customer service purposes.</p>
<h4>Text / SMS Marketing</h4>
<p>If you choose to opt-in to SMS communications from Luminar Capital, you will receive text messages at the mobile number you provide. These messages might be automated and might include promotional offers, coupons, and/or information related to Luminar Capital or our affiliated restaurants, as well as information related to your orders and account.</p>
<h5>Consent to Receive Automated Messages</h5>
<p>You understand that consent to receive automated messages is not a condition of purchase or use of Luminar Capital services. Messages may include but are not limited to, order confirmations, updates, and special offers.</p>
<h5>Confidentiality</h5>
<p>We will maintain the confidentiality of your mobile number. Your mobile number will not be shared with third parties for their own marketing purposes. However, for operational purposes, your name and mobile number may be shared with our service providers who assist in the delivery of our SMS communications. These providers use your personal information solely to carry out the services they provide to Luminar Capital.</p>
<h5>Frequency of Messages</h5>
<p>Message frequency may vary based on your orders, account activity, and ongoing promotions. You will receive messages relevant to your transactions and occasional promotional updates.</p>
<h5>Opt-Out and Support Options</h5>
<p>You may opt out of receiving text messages at any time by texting "STOP". Upon receipt of your opt-out request, you will be unsubscribed and will no longer receive text messages from us. A confirmation message will be sent to confirm your that you have unsubscribed. Should you wish to re-subscribe, you may text "START' to receive SMS messages again.</p>
<p>For assistance with the messaging service, text "HELP" or contact <a href="mailto:support@luminarcapital.com">support@luminarcapital.com</a>.</p>
<p>Wireless Carrier Rates and Services</p>
<p>Wireless carrier message and data rates may apply. Wireless carriers are not liable for delayed or undelivered messages.</p>
<h4>Cookies And Third-Party Analytics</h4>
<p>A cookie is a text file stored on a site visitor’s hard drive to help us improve your access to our Site and identify repeat visitors to our Site. Usage of a cookie is in no way linked to any personally identifiable information, though we can associate a cookie with any identifying information that is or has been provided to us while visiting our Site. We or our third-party service providers use cookies that remain on your computer for a specified period of time or until they are deleted (persistent cookies). These cookies record clickstream information (data reporting the URLs, or names of the pages, on our Site that have been visited). We may also use cookies that exist only temporarily during an online session (session cookies). These cookies allow us to identify you temporarily as you move through the Site. We also use cookies in the restricted client and sales representative limited-access portions of our Site. Most browsers allow users to refuse cookies, but doing so may impede the functionality of some portions of our Site.</p>
<h4>Social Media Widgets</h4>
<p>Our Site includes social media features, such as the Facebook like button and widgets, such as the “Share This” button or interactive mini-programs that run on our Site. These features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the feature to function properly. Social media features and widgets are either hosted by a third party or hosted directly on our Site. Your interactions with these features are governed by the privacy policy of the company providing it.</p>
<h4>Third Parties</h4>
<p>We may also engage third parties, including without limitation, Google Analytics and webtrends to track and analyze Site activity on our behalf. We use the data collected by such third parties to help us administer and improve the quality of the Site, analyze usage of the Site, and provide a more enhanced user experience on the Site, such as personalizing and delivering relevant offers and content based on user activity on the Site. The use of cookies by our third party partners is not covered by our Privacy Policy, as we do not have access or control over these cookies. We and some of our third party vendors and partners use technologies such as: cookies, beacons, tags and scripts in analyzing trends, administering our site, tracking users’ movements around the site and to gather demographic information about our user base as a whole. We may receive reports based on the use of these technologies by these companies on an individual as well as aggregated basis. If you wish not to be tracked, turn off javascript in your browser. However please note that without javascript turned on, our funding applications may not function as designed.</p>
<h4>Security</h4>
<p>Luminar takes reasonable steps to safeguard your personal information through physical, electronic, and operational policies and practices. Data can only be read or written through defined service access points, the use of which is password-protected. The physical security of the data is achieved through a combination of network firewalls (there is no direct communication allowed between the database server and the Internet) and servers with operating systems, all housed in a secure facility.</p>
<p>Access to the system is controlled. Employees are granted access to personal information on a need-to-know basis in order to perform a specific job (for example, billing or customer service). We use encryption to protect your personal information transmitted online, as well as offline. When we contact you about your account or to confirm a funds transfer, we only reference the last four digits of your social security number. The computers/servers in which we store personally identifiable information are kept in a secure environment.
We will also ensure the proper disposal of your personal information—regardless of the source.</p>
<h4>User Access</h4>
<p>If your personal information changes, or if you no longer want updates or to be contacted for new products, you may correct, update, amend, delete/remove or deactivate your contact information by emailing our customer support at <a href="mailto:support@luminarcapital.com">support@luminarcapital.com</a> or by contacting us by telephone or postal mail at the contact information listed below. We will update your file within 30 calendar days.</p>
<h4>Data Retention</h4>
<p>We will retain your information for as long as your account is active and thereafter as long as reasonably useful for internal purposes to improve our services and also to provide you with information in the future regarding our and our partners’ products and services. We may be required to retain your information to comply with our legal obligations, resolve disputes, and ensure the enforcement of agreements.</p>
<h4>Information Posted To Our Site</h4>
<p>We may, from time to time, allow users to post information to our Site, such as comments or testimonials. Any information that you post to our Site becomes public information and may be viewable by other users, as well as visitors to our Site (this is not true of uploaded documents as part of the funding process). In addition, your name, as well as other optional information you choose to submit along with the information you post, will be publicly displayed. We are not responsible for the privacy of any information that you choose to post to our Site, or for the accuracy of any information contained in those postings. We cannot prevent such information from being used by others in a manner that may violate this Privacy Policy, the law, or your personal privacy. Your posting of any content to any of the Site is subject to our Terms of Service.</p>
<h4>Third-Party Links</h4>
<p>At times, our Site may contain links to other, third-party websites. Any access to and use of such linked websites is not governed by this Privacy Policy but, instead, is governed by the privacy policies of those third-party websites. We are not responsible for the information practices of such third-party websites.</p>
<h4>International Users</h4>
<p>The Site is hosted in the United States. If you are accessing the Site from outside the United States, by providing your information to the Site, you are consenting to and authorizing the transfer of your information to the United States for storage, use, processing, maintenance, and onward transfer of such information to other entities regardless of their location in accordance with this Privacy Policy and our Terms of Service. You are also consenting to the application of United States law in all matters concerning the Site.</p>
<h4>Session Time Outs</h4>
<p>We also employ session time-outs to protect your account. You will be logged out of the Site automatically after a specified period of inactivity. This time-out feature reduces the risk of others being able to access your account if you leave your computer unattended.</p>
<h4>What You Can Do To Protect Your Personal Information</h4>
<p>In addition to our own efforts, you can take several precautions to protect the security of your computer and personal information. For instance, you should create and use a complex password, using numbers, a combination of small and large capital letters, and special characters. You should avoid using any information that others can easily learn about you, such as your mother’s maiden name, a family member’s name or birthday. We also recommend that you change your password frequently. You should never share your password with anyone, or leave it written down in an unsecure area.</p>

<p>You can also install and regularly update antivirus and firewall software to protect your computer or device from external attacks by malicious users. If you use a computer that can be accessed in a public area (e.g., library, coffee shop, etc.), we recommend that you take special precautions to protect the security of your account and personal information. When you are finished visiting our Site, you should log out completely, close the browser window and clear the browser’s cache files.</p>

<p>You should also be aware of fraudulent attempts to gain access to your account information known as “phishing.” Phishing is a tactic used by scammers to lure people to a phony website through the use of a genuine-looking email purporting to be from a legitimate company. Either in the email itself or on this fake website site, scammers will ask for login information to gain access to people’s accounts and withdraw their money. Luminar will never ask you for your login information in the context of any email. In general, you can protect yourself against phishing by never providing login or personal information via an email.</p>
<h4>Privacy Policy For California Residents</h4>
<p>The below information applies solely to California residents, including business owners, who have visited our website, inquired or submitted an application for business financing to Luminar Capital  and its subsidiaries (“Luminar Capital ”) or have been referred to Luminar Capital  by a third party and whose interactions with Luminar Capital  are subject to the California Consumer Protection Act (“CCPA”) and California Privacy Rights Act (“CPRA”).</p>
<h4>I. Why Do We Collect Your Personal Information?</h4>
<p>Luminar Capital  provides business financing to small businesses. In order to provide small business financing, we must collect information regarding the business as well as personal information from the business owner(s). Without obtaining this information, Luminar Capital  would be unable to provide financing as it would not have the information necessary to underwrite a request for financing. Furthermore, Luminar Capital  collects information regarding the business and personal information about the business owner(s) in order to improve the customer experience on our website, customer journey and client portal. Luminar Capital  also collects this data in order to assist the business in obtaining business financing from Luminar Capital . The information collected is kept indefinitely, unless we receive a request to delete from the client.</p>
<h4>II. What Personal Information Do We Collect?</h4>
<p>Luminar Capital  collects and maintains all information that the business owner(s) submits to Luminar Capital . This may include sensitive personal information about the business (e.g. business name, business address, business telephone number, business bank statements, credit card processing statements, federal tax identification number, financial statements, tax returns, email addresses, etc.) as well as sensitive personal information submitted by the business owner(s) to Luminar Capital (e.g. name, address, date of birth, driver’s license information, social security number, credit report information, telephone number, email addresses, etc.).</p>
<p>Luminar Capital  may also collect sensitive personal information about the business applicant and owner(s) which Luminar Capital receives from third parties. This information may be obtained by Luminar Capital from a third party that refers the business and business owner(s) to Luminar Capital and such information may include everything listed above that Luminar Capital  collects itself from businesses and their owners. This information may also be obtained by Luminar Capital from other third parties such as tax reporting services, bank account verification services, bank activity information providers, credit reporting services, landlords and neighbors, telephone number verification services, email verification services, IP address verification services, business status services, and credit card processing companies. Luminar Capital may disclose the aforementioned categories of personal information to third parties in order for third parties to provide business financing to the business or in order for third parties to assist Luminar Capital in its servicing or collection of past due accounts.</p>
<p>Luminar Capital also collects and maintains personal information that is indirectly provided to us by visiting our website(s) or any other online pages that we may maintain (whether accessed by computer or mobile phone). Specifically, Luminar Capital collects categories of information including: (i) information that is integral to maintaining the operation of our systems, which, for instance, helps us track which webpage you are viewing; (ii) marketing related scripts and cookies, such as how you got to our website; and (iii) user interaction scripts and cookies, which help us gather information on how you interact with our website. Furthermore, this includes information such as IP addresses, browser information, any other information collected via cookies, and geolocation. We collect this information on visitors in order to improve the client experience and ensure that the client is able to pick up where they left off during a visit to our website.</p>
<h4>III. Do We Sell Personal Information?</h4>
<p>Luminar Capital  does not sell any personal information to third parties. Luminar Capital  may share personal information to its service providers who have a need to know the information to assist Luminar Capital  and to third parties who will assist a small business applicant in obtaining financing for the business and will do so only with the business’s express written or verbal authorization.</p>
<p>Luminar Capital only provides business financing to businesses whose owners are eighteen (18) years or older and therefore does not collect nor sell the personal information of minors.</p>
<h4>IV. Right To Know And Right To Access</h4>
<p>Under the CCPA, a business owner residing in California has the right to request that Luminar Capital disclose what personal information it has collected, used, or disclosed about the business owner over the past 12 months. A business owner may submit a request to know up to twice a year, free of charge. A business owner that submits personal information to Luminar Capital can either personally or through an authorized agent, request the disclosure of the personal information that Luminar Capital collected and maintained within the previous twelve (12) months.</p>
<p>A business owner, or their authorized agent, that submits personal information to Luminar Capital may request the disclosure of personal information by submitting a verifiable request for information to: support@luminarcapital.com, or by calling our toll-free phone number at: (305) 307-0190. In order to be a verifiable request for information, the email or phone call must provide the following information: business name; business’s owner’s name; business address, business owner’s home address; business email, business owner’s email; business telephone number, and business owner’s telephone number.</p>
<p>Within ten (10) days after receipt of the verifiable information request, Luminar Capital will confirm that it is in receipt of the request and will utilize the information provided to lookup the relevant information in its internal systems so that it may determine what personal information of the business owner(s) Luminar Capital collected and maintains. Luminar Capital will respond to the request within forty-five (45) days after receipt of the request; however, if necessary, Luminar Capital may utilize an additional forty-five (45) days to respond to the request and will provide you with notice of the additional time.</p>
<h4>V. Right To Request Deletion Of Personal Information</h4>
<p>Under the CCPA, a business owner residing in California, or their authorized agent, has the right to request that Luminar Capital delete the personal information it has collected and maintains about the business owner(s). A business owner, or their authorized agent, may request the deletion of the personal information that Luminar Capital collected and maintains within the preceding twelve (12) months.</p>
<p>A business owner, or their authorized agent, may request the deletion of personal information, by submitting a verifiable request for deletion to: support@luminarcapital.com or by calling our toll-free phone number at: (305) 307-0190.</p>
<p>In order to be a verifiable request for deletion, the email must include the following: business name; business’s owner’s name; business address, business owner’s home address; business email, business owner’s email; business telephone number, and business owner’s telephone number.</p>
<p>Within ten (10) days after receipt of the verifiable deletion request received from the individual either by telephone or by email, Luminar Capital will confirm that it is in receipt of the request and will utilize the information provided to lookup the business owner’s information in its internal systems so that it may determine what personal information of the business Luminar Capital collected and maintains. Luminar Capital will respond to the request within forty-five (45) days after receipt of the request; however, if necessary, Luminar Capital and its subsidiaries may utilize an additional forty-five (45) days to respond to the request and will provide you with notice of the additional time.</p>
<p>Luminar Capital will not delete the business owner’s personal information to the extent the information is used: (1) to render a decision related to a financing request; (2) to service an outstanding financing product; (3) to prevent fraudulent or illegal activity; (4) for Luminar Capital’s internal use related to your relationship with Luminar Capital as well as Luminar Capital’s development of underwriting models, risk models, marketing models, and collection models; (5) for accounting or tax purposes and to comply with a legal obligation; or (6) for Luminar Capital’s internal use in a lawful manner that is compatible with the context in which the business owner(s) provided the personal information.</p>
<h4>VI. Right To Opt-Out Of Sale Of Personal Information</h4>
<p>Under the CCPA, a business owner residing in California, or their authorized agent, has the right to direct Luminar Capital to not to sell your personal information (the “right to opt-out”). Luminar Capital does not and will not sell personal information of business owners or their authorized agents.</p>
<h>VII. Right Of Non-Discrimination</h>
<p>Luminar Capital does not discriminate against any small business or small business owner(s) that exercises their right under the CCPA. Any small business or small business owner(s) that exercises their rights under the CCPA shall be treated the same as a small business or small business owner(s) that did not exercise its rights under the CCPA.</p>
<p>If you have any questions or concerns regarding Luminar Capital’s business practices and Privacy Policy for California Residents, please contact us at: support@luminarcapital.com, or you can call our toll-free phone number at: (305) 307-0190.</p>
<h4>Changes To This Policy</h4>
<p>We may update this Privacy Policy to reflect changes to our information practices. If we make any material changes we will post a revised policy on this Site prior to the change becoming effective. Your continued use of the Site shall constitute your acceptance of such updated Privacy Policy. We encourage you to periodically review this page for the latest information on our privacy practices.</p>
<p>By using our services, you acknowledge that you have read and understood the provisions of this privacy policy, including the CPRA compliance statement.</p>
`
