export const data: string = `
<p>Please read the following terms of service agreement carefully before using this website (“website”) located at luminarcapital.com.</p>
<p>The following are terms of a legal agreement (“agreement”) between you and Luminar Capital, LLC. (“Luminar Capital “or “company”) as the owners and operators of this website. If you do not agree to any of these terms, please leave the website immediately as you are not authorized to use it. By accessing, browsing, and/ or using this website or any portions of this website you acknowledge that you have read, understood these terms of service and, agree to be bound and abide by them.</p>
<h4>Modification To This Agreement</h4>
<p>These terms of service may be revised at the company’s sole discretion at any time, without prior notice. You are responsible for reviewing the terms of service periodically. Your continued access and/or use of the website following any change constitutes your agreement to any such revised terms of service.</p>
<h4>Intended Audience</h4>
<p>The services on this website are only intended for users located in the United States. Those who choose to access this website from other locations assume the responsibility of complying with applicable local laws. By using this website, you warrant that you are 18 years of age or older.</p>
<h4>Acceptable Use</h4>
<p>You may not access or use the website for any other purpose other than that for which the company makes it available. You may use the website only for lawful purposes and you agree that you shall at all times comply with all applicable local, state, provincial, national, and international laws, statutes, rules, regulations, ordinances, and the like applicable to your use of the website. You also agree that you will not do any of the following under any circumstances:</p>
<p>Submit to or on the website, anything that is or may be: (a) harmful, threatening, abusive, harassing, degrading, hateful, or intimidating; (b) defamatory, libelous, or disparaging of any person or entity; (c) false, fraudulent, or tortious; (d) obscene, indecent, pornographic, vulgar, profane, or sexually explicit; (e) intended to promote (or have the effect of promoting) violence, racial hatred, terrorism or illegal acts; (f) infringing, or in violation or misappropriation of, any patent, trademark, trade identity right, trade secret, publicity right, privacy right, copyright, or any other intellectual property right or any other rights of any third party; (g) in violation of any other rights of any person or entity; (h) in violation of any law or regulation; or (i) otherwise objectionable.</p>
<p>Impersonate any person or entity; falsely state or otherwise misrepresent your affiliation with any person or entity, including us; forge headers or otherwise manipulate identifiers in order to disguise the origin of any submissions to or through the website; or expressly state or imply that we endorse any statement you make.</p>
<p>Violate or attempt to violate the security of any portion of the website, including but not limited to: (a) access content not intended for you; (b) log into a server or account which you are not authorized to access; (c) attempt to probe, scan, or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (d) attempt to interfere with or disrupt the website or the servers or networks that provide the website, including without limitation, via means of submitting a virus to the website, overloading, “flooding”, “mailbombing” or “crashing” the website; or (e) restrict or inhibit any other user from accessing or using the website, including, without limitation, by means of hacking or defacing any portion of the website.</p>
<p>Modify, adapt, translate, reverse engineer, decompile, or disassemble any portion of the website.</p>
<p>Except as may be the result of a standard search engine or internet browser usage, using or launching, developing or distributing any automated system, including, without limitation, any spider, robot (or “bot”), cheat utility, scraper, or offline reader that accesses the websites, or using or launching any unauthorized script or other software.</p>
<h4>Communication</h4>
<p>You hereby expressly consent to receiving calls and messages, including auto-dialed and pre-recorded message calls and SMS messages (including text messages) from Luminar Capital, its affiliates, marketing partners, agents and others calling at Luminar Capital’s request or on its behalf, at any telephone numbers that you have provided or may provide in the future (Including any cellular or mobile telephone numbers). Your cellular or mobile telephone provider will charge you according to the type of plan you carry. You may opt out of receiving calls and marketing from Luminar Capital and its affiliates, marketing partners, agents and others as provided in the Privacy Policy or by contacting us directly.</p>
<h4>Term And Termination</h4>
<p>Without limiting its other remedies, company may immediately discontinue, suspend, terminate, or block your and any user’s access to this website and the related services or any portion thereof at any time in company’s sole discretion and without notice.</p>
<h4>Modification To This Website</h4>
<p>Luminar Capital shall reserve the right at any time it may deem fit, to modify, alter, add to, terminate, and/or suspend any part or all of the website at its own sole discretion at any time, without prior notice.</p>
<h4>Website Contents And Ownership</h4>
<p>Luminar Capital owns the intellectual property rights of all information on this website including but not limited to the company name, logo, graphics, videos, audios, images, designs, photographs, writings, graphs, data, and other materials. Company’s ownership rights are protected by copyrights, trademarks, trade secrets, or other proprietary rights. You shall comply with all copyright laws worldwide in your use of this website and prevent unauthorized copying. You may not copy, display, distribute, modify, reproduce, or transmit this website or portions thereof without prior written consent from company. Except as provided in this agreement, company does not grant you any express or implied right in or under any patents, trademarks, copyrights, or trade secret information.</p>
<h4>Third Parties</h4>
<p>The website may include links to other websites or applications operated by third parties. Luminar Capital has no control over such websites and resources or their terms of service. Such hyperlinks are provided for your reference only and their inclusion does not imply any sponsorship, affiliation, or endorsement of the material on such websites or with their operators. Material contained in linked websites does not necessarily reflect the views of Luminar Capital and we provide no warranty or representation in relation to the accuracy or completeness of such material. Your use of third-party websites is at your own risk.</p>
<h4>Consent To Electronic Transactions And Disclosures</h4>
<p>As Luminar Capital operates online, it is necessary for you to consent to transact business with us online and electronically. As part of doing business with us, therefore, we also need you to consent to us giving you certain disclosures electronically, either via our website, a third-party website or platform, or to the verified email address you provided during registration. By entering into this agreement, you consent to receive electronically all documents, communications, notices, contracts, and agreements arising from or relating in any way to your or our rights, obligations or services under this agreement (each, a “disclosure”). This document informs you of your rights concerning disclosures.</p>
<p>Electronic Communications. Any disclosures will be provided to you electronically, either on our website, a third-party website or platform, or via electronic mail to the verified email address you provided during registration. Your consent to electronic delivery will apply to all future communications unless consent is withdrawn by you. If you require paper copies of such disclosures, you may write to us at the mailing address provided below and a paper copy will be sent to you.</p>
<p>Scope of Consent. Your consent to receive disclosures and transact business electronically, and our agreement to do so, applies to any transactions to which such disclosures relate.</p>
<p>Consenting to Do Business Electronically. Before you decide to do business electronically with us, you should consider whether you have the required hardware and software capabilities described below.</p>
<p>Hardware and software requirements. In order to access and retain disclosures electronically, you must satisfy the following computer hardware and software requirements: access to the internet; an email account and related software capable of receiving email through the internet; a web browser that is SSL-compliant and supports secure sessions, and hardware capable of running this software.</p>
<p>For more information regarding Electronic Disclosures, please contact us.</p>
<p>You are responsible for keeping us informed of any change in your email or home mailing address so that you can continue to receive all disclosures in a timely fashion. You also agree to update your registered residence address, and telephone number on the website if they change.</p>
<p>You agree to print a copy of this agreement for your records. You agree and acknowledge that you can access, receive, and retain all disclosures electronically sent via email or posted on the website.</p>
<h4>Liability Disclaimer</h4>
<p>Luminar Capital makes no representations about the suitability, reliability, availability, timeliness, and accuracy of the information, software, products, services, and related graphics contained on the website for any purpose. To the maximum extent permitted by applicable law, all such information, software, products, services, and related graphics are provided “as is” without warranty or condition of any kind. Luminar Capital and/or its suppliers hereby disclaim all warranties and conditions with regard to this information, software, products, services, and related graphics, including all implied warranties or conditions of merchantability, fitness for a particular purpose, title, and non- infringement. To the maximum extent permitted by applicable law, in no event shall Luminar Capital and/or its suppliers be liable for any direct, indirect, punitive, incidental, special, consequential damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the website, with the delay or inability to use the website or related services, the provision of or failure to provide services, or for any information, software, products, services, and related graphics obtained through the website, or otherwise arising out of the use of the website, whether based on contract, tort, negligence, strict liability or otherwise, even if the company has been advised of the possibility of damages. Because some states/jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you. If you are dissatisfied with any portion of the website, or with any of these terms of use, your sole and exclusive remedy is to discontinue using the website.</p>
<h4>Assumption Of Risk</h4>
<p>You expressly agree that the use of this website is done at your own risk. The information published on this website is for informational purposes only. Any reliance you place on such, you do at your own risk. You understand that while great care is taken to provide you with the best information possible, company makes no representations or warranties of any kind, express or implied, about the reliability, accuracy, completeness, security, or currency of the information provided.</p>
<h4>Indemnification</h4>
<p>You agree to indemnify, defend, and hold harmless Luminar Capital, LLC, its affiliates, agents, employees, and licensors from and against any and all claims and expenses, including reasonable attorney fees, arising out of or related in any way to your use of the website, violation of this agreement, violation of any law or regulation, or violation of any proprietary or privacy right.</p>
<h4>Dispute Resolution</h4>
<p>This agreement is governed by and shall be construed in accordance with the laws of Delaware, U.S.A. without reference to its conflict-of-law provisions. You agree to submit to the personal and exclusive jurisdiction in Delaware, U.S.A. for any disputes with company arising out of your use of this website. You agree that if a dispute arises, parties will attempt to resolve the dispute with mediation in Delaware, U.S.A., or an online mediation service that is mutually agreed upon by all parties. The parties agree that their good faith participation in mediation is a condition precedent to pursuing other legal remedies. The successful party to any dispute resolution will be entitled to reasonable costs and fees incurred in resolving or settling the dispute, in addition to any other relief to which the party may be entitled.</p>
<h4>Entire Agreement</h4>
<p>This agreement constitutes the entire agreement between Luminar Capital and you with respect to this website. This agreement supersedes and cancels all prior or contemporaneous discussions, writings, negotiations, and agreements whether electronic, oral, or written between you and company with respect to this website. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based on or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
<h4>Severability</h4>
<p>If any term in this agreement is found to be void or voidable, the remaining terms of the agreement are unaffected and deemed to remain in full force and effect, including those terms that are similar.</p>
<h4>No Waiver</h4>
<p>Company’s failure to enforce its rights under this agreement or take action against any party for breach of this agreement does not constitute a waiver of such rights, or of future subsequent enforcement of such rights.</p>
<h4>Notification of Infringement</h4>
<p>If you are a copyright owner or an agent thereof and believe in good faith that any content on this website infringed your copyrights, you should send us an infringement notice pursuant to the Digital Millennium Copyright Act (“DMCA”). To file a notice with this website, send a written communication to Luminar Capital copyrights agent and provide the following information in writing:</p>
<ul>
	<li>Identification of the copyrighted work that you claim has been infringed.</li>
	<li>Identification of the specific material that is claimed as infringing and information sufficient to permit the website to locate that material on our website or within the communication service.</li>
	<li>A statement that you believe, in good faith, that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or by law.</li>
	<li>If you are not the copyright owner, a description of your relationship to the copyright owner.</li>
	<li>Your contact information, including your address, telephone number and email address.</li>
	<li>A physical or electronic signature of a person authorized to act on behalf of the copyright owner.</li>
</ul>
<h4>Privacy</h4>
<p>For information about how the company collects, uses, and shares your information, please review our Privacy Policy. You agree that by using the services you consent to the collection, use, and sharing (as set forth in the privacy policy) of such information.</p>
`
